### ISSUE TITLE
nGrok error when I using trape

### ISSUE THREAD

**Issue by slowhollic** [jofpin/trape#141]

**Comment by DJCHICKEN4** [comment]
@slowhollic Try reinstalling trape because a patch got merged yesterday that should fix this.

**Comment by slowhollic** [comment]
@DJCHICKEN4 thanks for your reply, I will do it tomorrow.

**Comment by Rainam** [comment]
> @slowhollic Try reinstalling trape because a patch got merged yesterday that should fix this.

PLEASE NOTE THAT THE PATCH DIDN'T FIX THE ISSUE. IF POSSIBLE HELP OVERCOME THE PROBLEM. THANKS!
